Step 8 True/False: Added the Delete question function

diff --git a/Study b/Study
--- a/Study
+++ b/Study
@@ -455,28 +455,88 @@ done
 # Step 8: Delete Question
 #      #------------------- T/F Questions ------------------------------------
   # Todo:
-  # - check if file is not empty
+delete_true_false_question() {
+  # - check if file is not empty 
+  if [ ! -s "$true_false_file" ]; then
+	  echo "The True/False question file is empty"
+	  return 
+  fi 
+
+  while true; do
   # - show the quesion in a list formaat
+     echo "True/False Questions: "
   #    - $((i+1)) ${tru_false_question[$i]}
-  #
+     for i in "${!true_false_question[@]}"; do
+	     echo "$((i + 1)). ${true_false_questions[$1]}"
+     done
+
   # - Ask user the number of the question they want to delte
   # - Validate input
+      read -p "Enter the Number of the question you want to delete ( or 'q' to return to the menu): " choice
+      
+      if [[ "$choice" == "q" ]]; then
+	      echo "Returning to the menu"
+	      break
+      fi 
+	
+      if ! [[ "$choice" =~ ^[0-9]+$ ]] || [ "$choice" -lt 1 ] || [ "$choice" -gt "${#true_false_questions[@]}" ]; then
+	      echo "Invalid Input, Please enter a valid question number."
+	      continue
+      fi
+
   # - remove the question from the array
+     index=$((choice -1 ))
+     echo  "Deleting: ${true_false_question[$index]}"
+     unset true_false_question[$index]
+
   # - rewrite the True/False question to the file without the deleted question
+     echo "${true_false_questions[@]}" > "$true_false_file"
+     echo "Question deleted successfully!"
+   
+  # - Ask the user if they want to delete another question
+     read -p "Do you want to delete another question? (y/n): " user_response
+     if [[ "$user_response" != "y" && "$user_response" != "Y" ]]; then
+	     echo "Returning to the Menu"
+	     break
+     fi 
+ done
+}
 #      #------------------- MCQ Questions ------------------------------------
   # Todo:
+delete_MQ_questions() {
   # - check if file is not empy
-  # - show the questions in a list format
+  if [ ! -s "$multiple_choice_file" ]; then
+	  echo "The Multiple Choice Question File is empty"
+	  return
+  fi 
   
+  while true; do 
+  # - show the questions in a list format
+      echo "Multiple Choice Questions:"
+      for i in "${!multiple_choice_questions[@]}"; dp
+	      questions="${multiple_choice_questions[$1]}"
+	      question_tex
   # - ask the user the number of the question they want to delete
   # - Validate input 
   # - remove the question from the array
   # - rewrite the True/False question to the file without the deleted question
-
+ done
+}
 #      #------------------- Command Questions ---------------------------------
   # Todo
-  # wad:wq
+  # - Check if the th Command File is not empty:
+  # - Show the question in anumbered list format
+  # 	- $((i+1)) ${commandS_question[$i]}
+  # 
+  # - Ask th user to enter the number corresponding to the question they want to delete
+  # - Validate the input:
+  # 	- Ensure the input is a number
+  # 	- Ensure the number corresponsds to an existing question in the list
   #
+  # - Remove the question from the array
+  # - Rewrite the command question the the file, excluding the deleted question
+  # - Confirm to the user that the question was susccessfully deleted
+  
   
 
 
@@ -518,4 +578,4 @@ done
    # - call the associate function
    # - error handling - invalid input
 # }
-#
+#x
